In [1]:
import numpy as np
from PIL import Image

In [32]:
a, b, step = -2, 2, 0.001 # start, stop, and step values for the 'window'.
# N = np.arange(a, b+step, step)
w, h = 4000, 4000
X = np.linspace(-2, 2, w)
Y = np.linspace(-2, 2, h)
# N_2 = 

def cartesian_product(x, y):
    return np.transpose([np.tile(x, len(y)), np.repeat(y, len(x))])

# c_0 = cartesian_product(N, N)
c_0 = cartesian_product(X, Y)

# print(N)
print(c_0)

# convert the 2D array into an array of complex numbers. 
c_0_i = 1j*c_0[...,1] # build the complex components
c_0_i += c_0[...,0] # build the real components

print(c_0_i)

[[-2.         -2.        ]
 [-1.99899975 -2.        ]
 [-1.9979995  -2.        ]
 ...
 [ 1.9979995   2.        ]
 [ 1.99899975  2.        ]
 [ 2.          2.        ]]
[-2.        -2.j -1.99899975-2.j -1.9979995 -2.j ...  1.9979995 +2.j
  1.99899975+2.j  2.        +2.j]


In [43]:
# z_(n+1) = z_(n)^2 + c 
# c = some complex number.
# z_0 = 0
# iteration applied repeatedly. 

# try it the basic "dumb" way first!
z = 1j * np.zeros(len(c_0)) # z_0 = 0

# z = 1j * np.random.random(len(c_0)) + np.random.random(len(c_0)) # z_0 = random

for n in range(60):
    z = z**2 + c_0_i
    
print(z[abs(z)<1])
bounded = z[abs(z)<1]
print(len(c_0_i), len(bounded))
print(len(c_0_i)**(1/2))
print(max(abs(z)))

# other ideas: Use quaternions in the formula, visualize in 4D as a video, or reduce to 3 values and visualize in 3D!

# IDEA: Parallelize across pixels to determine which iteration the pixel exceeds a cutoff value. 
# have a map across all the pixels, then calculate which iteration each pixel exceeds some cutoff. 

/home/brian/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:12: RuntimeWarning: overflow encountered in square
  if sys.path[0] == '':
/home/brian/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in square
  if sys.path[0] == '':
/home/brian/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:14: RuntimeWarning: invalid value encountered in less
  


[-0.0008718 +0.00278099j  0.31329044+0.40711572j  0.07485824+0.07272151j
 ...  0.07485824-0.07272151j  0.31329044-0.40711572j
 -0.0008718 -0.00278099j]


/home/brian/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:15: RuntimeWarning: invalid value encountered in less
  from ipykernel import kernelapp as app


16000000 1569140
4000.0
nan


In [57]:
import matplotlib as plot


# Create high contrast between positive and negative space of the fractal
# pos_space = [<primary_colors...>] # cardnality of set determines visual complexity (could be function)
# Instead of 'h = (360 - np.log(abs(c)) % (180)) / (360)' - 
# (c) => return 'position in pos_space 

# neg_space = [<secondary_colors...>] # cardnality of set determines visual complexity (could be function)
# Instead of 'h[np.isnan(c)] = 90 / 360 ' - 
# (c) => return 'position in neg_space

# map absolute values to hues.
def color_map(c):
    # IDEA: Use black for values below some cutoff, and hues for values above that. 
    h = (360 - np.log(abs(c)) % (180)) / (360) # calculate hue.
#     h[c<1] = 0
    
    h[np.isnan(c)] = 90 / 360 
    
    hsv = np.column_stack((h, np.ones(len(h)), np.zeros(len(h)) + 0.5))
    rgb = plot.colors.hsv_to_rgb(hsv)
#     rgb[np.isnan(c)] = np.zeros(3)
    rgb_int = (rgb * 256).astype(np.uint8) 
    return rgb_int

z_rgb = color_map(z)
print(z_rgb)
# rearrange the 1D array of hue values to 2D.
# s = int(len(z_rgb)**(1/2))
img = Image.fromarray(z_rgb.reshape(w,h,3))
img.show()

/home/brian/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:16: RuntimeWarning: invalid value encountered in remainder
  app.launch_new_instance()


[[ 64 128   0]
 [ 64 128   0]
 [ 64 128   0]
 ...
 [ 64 128   0]
 [ 64 128   0]
 [ 64 128   0]]


In [26]:
# data = np.zeros( (1024,1024,3), dtype=np.uint8 )

# data[512,512] = [254,0,0]       # Makes the middle pixel red
# data[512,513] = [0,0,255]       # Makes the next pixel blue

# img = Image.fromarray( data )       # Create a PIL image
# img.show()    
